volumes:
  pg_cafe:

services:
  cafe_db:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=cafe_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=my0Pass1'
    volumes:
      - pg_cafe:/var/lib/postgresql/data
    ports:
      # Порт для серверного приложения и для контейнера с базой данных.
      - '127.0.0.1:5432:5432'

