name: "bootcupscoffebar"

volumes:
  pg_cafe:

services:
  cafe_db:
    image: 'postgres:latest'
    restart: always

    container_name: "database"

    env_file:
      - path: "secrets.env"
        required: true

    environment:
      POSTGRES_DB: "${POSTGRES_DB}"

    volumes:
      - pg_cafe:/var/lib/postgresql/data
    ports:
      # Порт для контейнера, запущенного на локальной машине и для СУБД.
      - "${DATABASE_PORT:-5432}:5432"