volumes:
  pg_cafe:

services:
  cafe_db:
    image: 'postgres:latest'
    restart: always
    env_file:
      - .env
    container_name: 'cafebar-postgres-db'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DATABASE:-postgres}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}'
    volumes:
      - pg_cafe:/var/lib/postgresql/data
    ports:
      # Порт для контейнера, запущенного на локальной машине и для СУБД.
      - '${DATABASE_PORT:-5432}:5432'