server:
  port: ${SERVICE_PORT}


spring:

  application:
    name: "bootcupscoffeebar"

  datasource:
    url: "jdbc:postgresql://${SERVICE_HOST}:${DATABASE_PORT}/${POSTGRES_DB}"

    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: 'classpath:db/changelog/changelog-master.yaml'

  thymeleaf:
    mode: 'HTML'
    encoding: 'UTF-8'
    prefix: 'file:src/main/resources/templates/'
    static-locations: 'file:src/main/resources/static/'

  messages:
    basename: "i18n/messages"
    fallback-to-system-locale: false
    cache-duration: 60


logging:
  level:
    ru.manannikov.bootcupscoffeebar: DEBUG


telegram:
  bot:
    name: ${TELEGRAM_BOT_NAME}
    token: ${TELEGRAM_BOT_TOKEN}