spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: 'cafeBarBusinessSystem'

  datasource:
    url: 'jdbc:postgresql://${APP_HOST:localhost}:${DATABASE_PORT:5432}/${POSTGRES_DATABASE:postgres}'
    username: '${POSTGRES_USERNAME:postgres}'
    password: '${POSTGRES_PASSWORD:postgres}'

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: 'classpath:db/changelog/changelog-master.yaml'

  thymeleaf:
    mode: 'HTML'
    encoding: 'UTF-8'
    prefix: 'file:src/main/resources/templates/'
    static-locations: 'file:src/main/resources/static/'

server:
  port: ${APP_PORT:8080}